### ISSUE TITLE
userId 필드 추가 생성 요청 건

### ISSUE THREAD

**Issue by WachsenHaus** [dduckddack-coinTalk/chatroom#1]
payload.user안에 userId라는 필드가 추가된다면 기존 닉네임에서 userId (number)값으로 필터링하여 클라이언트에서 표시하는데 문제가 없을 것으로 판단됩니다.

![스크린샷 2022-05-16 오후 10 59 31](https://user-images.githubusercontent.com/59411545/168612340-995cbe34-1423-4883-82a2-ed3e04218661.png)

# 요청 
payload.user.userId 필드 추가 요청드립니다.

**Comment by HayanYoo** [comment]
{
   "type":"CHAT_MESSAGE",
   "payload":{
         "roomId":"비트코인",
         "user":{
               "username":"익명",
               "avatar":"", 
               "userId":2
                },
          "message":"id test"
       }
}

요청하신 부분 수정하였습니다.
userId는 Number type으로 위와같이 request 주시면 됩니다

확인 후 정상 작동하면 Close 부탁드립니다. 😏

**Comment by WachsenHaus** [comment]
잘 동작합니다. 감사합니다 ^_^
